package options

type RemedyControllerOptions struct {
	// command line options

	// PermanentConditions specifies the list of conditions monitored by node problem detector.
	PermanentConditions []string

	// TemporaryEvents specifies the kind of events generated by node problem detector.
	TemporaryEvents []string
}

func NewRemedyControllerOptions() *RemedyControllerOptions {
	return &RemedyControllerOptions{}
}
