---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: remedy-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: remedy-controller
subjects:
- kind: ServiceAccount
  name: remedy-controller
  namespace: default

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: remedy-controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - events
  verbs:
  - watch
  - list
  - update
  - get
  - patch
  - create

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: remedy-controller
  namespace: default
  labels:
    kubernetes.io/cluster-service: "true"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: remedy-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s.app: remedy-controller
  template:
    metadata:
      name: remedy-controller
      labels:
        k8s.app: remedy-controller
    spec:
      serviceAccountName: remedy-controller
      containers:
      - image: remedy-controller
        imagePullPolicy: IfNotPresent
        name: remedy
        command:
        - /remedy-controller
        - --logtostderr=true
        - --v=2
        - --monitors=/config/kernel-monitor.json
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: node-problem-detector-config
      - name: localtime
        hostPath:
          path: /etc/localtime
